# RabbitMQ Role Handlers
---
- name: restart rabbitmq
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: restarted
    daemon_reload: yes
  listen: "restart rabbitmq"

- name: reload rabbitmq
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: reloaded
  listen: "reload rabbitmq"

- name: stop rabbitmq
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: stopped
  listen: "stop rabbitmq"

- name: start rabbitmq
  ansible.builtin.systemd:
    name: rabbitmq-server
    state: started
  listen: "start rabbitmq"
